"""Dashboard: overview stats, category breakdown, spending trend, insights.

Every number on this page comes from app/analytics running over
confirmation_status='confirmed' transactions only — see
docs/ARCHITECTURE.md for why pending (unverified) extractions are
excluded.
"""

from datetime import date

import plotly.express as px
import streamlit as st

from app.analytics import metrics as m
from app.analytics.insights import generate_insights
from app.database import repository as repo
from app.utils.formatting import format_amount


def render() -> None:
    st.header("Dashboard")

    transactions = repo.list_transactions(status="confirmed")
    df = m.transactions_to_dataframe(transactions)

    if df.empty:
        st.info(
            "No confirmed transactions yet. Upload a receipt and confirm it "
            "on the Upload page to see your dashboard."
        )
        return

    today = date.today()
    month_start = today.replace(day=1)
    this_month_df = df[(df["transaction_date"] >= _ts(month_start)) & (df["transaction_date"] <= _ts(today))]

    _render_overview(this_month_df)
    st.divider()

    left, right = st.columns(2)
    with left:
        _render_category_breakdown(this_month_df)
    with right:
        _render_trend(df)

    st.divider()
    _render_insights(df, today)


def _ts(d):
    import pandas as pd
    return pd.Timestamp(d)


def _render_overview(this_month_df) -> None:
    st.subheader("This Month")
    stats = m.overview_stats(this_month_df)
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Spending", format_amount(stats["total_spending"]))
    col2.metric("Transactions", stats["transaction_count"])
    col3.metric("Average Transaction", format_amount(stats["average_transaction"]))
    if stats["largest_expense"]:
        col4.metric(
            "Largest Expense",
            format_amount(stats["largest_expense"]["amount"]),
            help=f"{stats['largest_expense']['merchant']} on {stats['largest_expense']['date']}",
        )
    else:
        col4.metric("Largest Expense", "—")


def _render_category_breakdown(this_month_df) -> None:
    st.subheader("Category Breakdown (This Month)")
    breakdown = m.category_breakdown(this_month_df)
    if not breakdown:
        st.caption("No confirmed transactions this month yet.")
        return

    for row in breakdown:
        st.write(f"**{row['category']}** — {format_amount(row['total'])} ({row['share_pct']}%)")

    fig = px.pie(
        breakdown, names="category", values="total", hole=0.5,
    )
    fig.update_layout(showlegend=True, margin=dict(t=10, b=10, l=10, r=10))
    st.plotly_chart(fig, use_container_width=True)


def _render_trend(df) -> None:
    st.subheader("Spending Trend (Monthly)")
    monthly = m.monthly_spending(df)
    if not monthly:
        st.caption("Not enough data yet.")
        return
    fig = px.bar(monthly, x="month", y="amount", labels={"month": "Month", "amount": "Spending"})
    fig.update_layout(margin=dict(t=10, b=10, l=10, r=10))
    st.plotly_chart(fig, use_container_width=True)


def _render_insights(df, today) -> None:
    st.subheader("Spending Insights")
    st.caption("Computed directly from your confirmed transactions — not generated by an LLM.")
    for insight in generate_insights(df, as_of=today):
        st.markdown(f"- {insight}")
