"""Train the optional ML category classifier and print/save honest evaluation metrics.

Run: python scripts/train_classifier.py
Reads:  data/training_data.csv (generate first with generate_training_data.py)
Writes: data/classifier_model.pkl, docs/ML_METRICS.md (actual measured results)
"""

import csv
import json
from pathlib import Path

from app.classification.ml_classifier import train_and_evaluate, save_model

DATA_PATH = Path(__file__).resolve().parents[1] / "data" / "training_data.csv"
METRICS_DOC_PATH = Path(__file__).resolve().parents[1] / "docs" / "ML_METRICS.md"


def load_dataset() -> tuple[list[str], list[str]]:
    texts, labels = [], []
    with open(DATA_PATH, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            texts.append(row["text"])
            labels.append(row["category"])
    return texts, labels


def write_metrics_doc(metrics) -> None:
    rows = "\n".join(
        f"| {label} | {' | '.join(str(v) for v in row)} |"
        for label, row in zip(metrics.labels, metrics.confusion_matrix)
    )
    content = f"""# ML Classifier — Measured Evaluation Results

Generated by `scripts/train_classifier.py`. These are the actual numbers
from the most recent training run on `data/training_data.csv` — not
estimates. Re-run the script to reproduce (random_state is fixed, so the
split is deterministic).

- Training examples: {metrics.n_train}
- Test examples (held out, 25% split): {metrics.n_test}
- Accuracy (test set): **{metrics.accuracy}**
- Macro precision: **{metrics.precision_macro}**
- Macro recall: **{metrics.recall_macro}**
- Macro F1: **{metrics.f1_macro}**

## Confusion matrix (rows = actual, columns = predicted, order = {metrics.labels})

| actual \\ predicted | {' | '.join(metrics.labels)} |
|---|{'---|' * len(metrics.labels)}
{rows}

## Reading these numbers honestly

This model is trained on {metrics.n_train + metrics.n_test} synthetic,
templated examples — not real receipts. High accuracy here reflects that
the synthetic categories use fairly distinct vocabulary, not that the
model would generalize this well to messy real-world OCR text with typos,
unfamiliar merchants, or ambiguous wording. Treat this as a documented
proof-of-concept, not a production accuracy claim. See
`docs/ML_PIPELINE.md` for the full discussion and why the rule-based
categorizer, not this model, is the default.
"""
    METRICS_DOC_PATH.write_text(content)


def main() -> None:
    if not DATA_PATH.exists():
        raise SystemExit(
            f"{DATA_PATH} not found. Run scripts/generate_training_data.py first."
        )

    texts, labels = load_dataset()
    pipeline, metrics = train_and_evaluate(texts, labels)
    save_model(pipeline)
    write_metrics_doc(metrics)

    print(json.dumps({
        "accuracy": metrics.accuracy,
        "precision_macro": metrics.precision_macro,
        "recall_macro": metrics.recall_macro,
        "f1_macro": metrics.f1_macro,
        "n_train": metrics.n_train,
        "n_test": metrics.n_test,
    }, indent=2))
    print(f"\nModel saved. Metrics written to {METRICS_DOC_PATH}")


if __name__ == "__main__":
    main()
